# Generated by Django 6.0.3 on 2026-03-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='replace_existing',
            field=models.BooleanField(default=False, help_text="If True, replaces existing file with same name. If False, adds '123' suffix."),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('purchase', 'Purchase'), ('cancel_Payment', 'Cancel Payment'), ('failed_login', 'Failed Login Attempt'), ('password_change', 'Password Change')], max_length=20),
        ),
    ]
