# Generated by Django 6.0.3 on 2026-03-22 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mediaasset_replace_existing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='duration',
            field=models.FloatField(blank=True, editable=False, help_text='Duration in seconds', null=True),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='extension',
            field=models.CharField(blank=True, editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='file',
            field=models.FileField(max_length=500, upload_to='media_library/'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='mediacat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='core.mediaalbum'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='replace_existing',
            field=models.BooleanField(default=False),
        ),
    ]
