# Generated by Django 6.0.3 on 2026-04-22 11:20

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mediaasset_duration_mediaasset_extension_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaasset',
            name='file',
            field=models.FileField(max_length=500, upload_to=core.models.media_library_path),
        ),
    ]
