# Generated by Django 6.0.3 on 2026-04-25 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_mediaasset_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout_type', models.CharField(choices=[('hero', 'Hero Slider (Widget Preferred)'), ('standard', 'Standard (Text & Image)'), ('icons', 'Icon Grid (Features)'), ('testimonial', 'Testimonials Carousel'), ('info', 'Info Bar (Strip)'), ('widget_box', 'Custom Widget Box')], default='standard', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.page')),
                ('widget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.widget')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
