# Generated by Django 6.0.3 on 2026-05-16 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenthistory',
            name='purchase_id',
        ),
    ]
