# Generated by Django 6.0.3 on 2026-04-26 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_full_name_address_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='Country',
            new_name='country',
        ),
    ]
