# Generated by Django 6.0.3 on 2026-05-02 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.productvariant'),
        ),
        migrations.AddField(
            model_name='ordertracking',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_history', to='order.order'),
        ),
        migrations.AddField(
            model_name='ordertracking',
            name='status_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.trackingstatus'),
        ),
    ]
