# Generated by Django 6.0.3 on 2026-05-10 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='note',
            new_name='order_notes',
        ),
    ]
